### ISSUE TITLE
No longer resolves piped promises from imported async functions

### ISSUE THREAD

**Issue by victorlearned** [Sullux/fp-light#29]
Apparently resolve no longer correctly deepAwaits imported functions in the latest. I know for sure this worked everywhere in `1.2.3` but seems to sporadically break when upgrading to anything higher. Here's an example that works in `1.2.3` but breaks on anything higher with an unresolve promise for the `invoke`

```
const aws = require('@sullux/aws-sdk')();
const { invokeLambdaFactoryHelper } = require('./invokeLambda');

const { invoke } = aws.lambda;

const invokeLambdaFactory = invokeLambdaFactoryHelper({ invoke });

module.exports = { invokeLambdaFactory };
```

```
const {
  _,
  pipe,
  tap,
} = require('fp-latest');

const invokeLambdaFactoryHelper = ({
  invoke,
}) => {
  const assertLambdaSucceeded =
  tap(({ FunctionError, LogResult, Payload }) => {
    if (!FunctionError) {
      return undefined;
    }
    console.log('Lambda logs: ', JSON.stringify(LogResult, null, 2));
    const { errorType, errorMessage } = JSON.parse(Payload);
    const error = new Error(`${FunctionError} error: ${errorMessage}`);
    error.code = errorType;
    return Promise.reject(error);
  });

  // functionName can be the funciton name or funciton ARN
  const invokeLambdaFactory = (functionName) =>
    pipe(
      {
        FunctionName: functionName,
        Payload: JSON.stringify,
      },
      invoke, // FP 1.2.28 no longer correctly figures nested/imported async funcs need to be awaited
      // async (input) => await invoke(input), // IF I swap this in it resolves correctly
      tap((input) => console.log('invokeLambdaFactory INVOKE ', input)),
      assertLambdaSucceeded,
      _.Payload,
      JSON.parse,
    );

  return invokeLambdaFactory;
};

module.exports = { invokeLambdaFactoryHelper };
```

**Comment by Sullux** [comment]
Yeah, that functionality broke as part of the performance tuning. I think it can be added back now. I'll do a red light/green light and let you know when I publish the fix.

**Comment by Sullux** [comment]
Ok, I published version 1.2.29 that should properly await promises in resolved objects/arrays. Let me know if that works for you.

**Comment by victorlearned** [comment]
Cool. I'll give it a spin. 

There's definitely another bug related it how after the perf updates with added symbols, fp can no longer handle non-extensible object as input. Example is in bb1 wrapper it's tagging events with `Symbol('eventInfo')` and `Object.freeze` before handing it off. Then fp latest immediately chokes when it eventually tries to move thru `deepAwait` and add the `Symbol('sync')` tag.

**Comment by victorlearned** [comment]
I'm still seeing promises being returned at least in just my tests:

```
  console.log src/utils/invokeLambda/invokeLambda.js:30
    invokeLambdaFactoryHelper invoke result:  Promise {
      {
        Payload: '{"result":"successful invoke"}',
        FunctionError: null,
        LogResult: null
      }
    }

  console.log src/utils/invokeLambda/invokeLambda.js:30
    invokeLambdaFactoryHelper invoke result:  Promise {
      {
        Payload: '{"errorType":"ERROR","errorMessage":"This is a big error"}',
        FunctionError: 'BIG ERROR',
        LogResult: { log: 'test log result' }
      }
    }
  ```
  
  Tests are pretty simple:
  
  ```
  const { invokeLambdaFactoryHelper } = require('./invokeLambda');

const functionName = 'myFunction';
const event = { foo: 'bar' };
const successfulLambdaPayload = { result: 'successful invoke' };

describe('invokeLambda', () => {
  const mockDependencies = ({
    lambdaError = null,
    lambdaPayload = successfulLambdaPayload,
    lambdaLogResult = null,
  }) => ({
    invoke: jest.fn().mockResolvedValue({
      Payload: JSON.stringify(lambdaPayload),
      FunctionError: lambdaError,
      LogResult: lambdaLogResult,
    }),
  });

  it('should call invoke with functionName and event and return parsed payload', async () => {
    const dependencies = mockDependencies({});
    const invokeLambdaFactory = invokeLambdaFactoryHelper(dependencies);
    const invokeLambda = invokeLambdaFactory(functionName);

    const result = await invokeLambda(event);

    expect.assertions(2);
    expect(dependencies.invoke).toHaveBeenCalledWith({
      FunctionName: functionName,
      Payload: JSON.stringify(event),
    });
    expect(result).toEqual(successfulLambdaPayload);
  });

  it('should throw on error', async () => {
    const lambdaPayload = { errorType: 'ERROR', errorMessage: 'This is a big error' };
    const lambdaError = 'BIG ERROR';
    const lambdaLogResult = { log: 'test log result' };
    const dependencies = mockDependencies({ lambdaPayload, lambdaError, lambdaLogResult });
    const invokeLambdaFactory = invokeLambdaFactoryHelper(dependencies);
    const invokeLambda = invokeLambdaFactory(functionName);

    expect.assertions(2);
    try {
      await invokeLambda(event);
    } catch (e) {
      expect(e.message).toEqual(`${lambdaError} error: ${lambdaPayload.errorMessage}`);
    }
    expect(dependencies.invoke).toHaveBeenCalledWith({
      FunctionName: functionName,
      Payload: JSON.stringify(event),
    });
  });
});
```

**Comment by Sullux** [comment]
The frozen object problem I can definitely fix. That one's easy. I'll jump on it now.

As to the Promise problem, do you think you could provide an example that doesn't have external dependencies? For example, my red/green test I used to validate this fix looks like this:

```javascript
  test('should deep await', async () => {
    const fn = resolve({
        foo: [Promise.resolve(42)],
        bar: Promise.resolve('baz'),
        value: _,
      })
    const result = await fn('biz')
    expect(result).toEqual({ foo: [42], bar: 'baz', value: 'biz' })
  })
```

**Comment by victorlearned** [comment]
Weird it might just be an odd jest mock thing. Seems to mock and tested a deployed lambda doing a direct axios call and it worked. Then just seems to be the extensible issue.

**Comment by Sullux** [comment]
Yes, I have seen lots of goofy behavior from Jest mocking. I'm thinking back and I may have even had to change a setting in the test config on one project to tell it to stop auto-mocking stuff (but I could be mistaken).

In any case, as to the frozen objects, you should be all set with version `1.2.30` that I just published.

**Comment by victorlearned** [comment]
I'll try your new update today.

What I was seeing on `28` and on `29` was:

**Jest working for certain mocks and not others:**

```
// original version which doesn't work still
    invoke: jest.fn().mockResolvedValue({
      Payload: JSON.stringify(lambdaPayload),
      FunctionError: lambdaError,
      LogResult: lambdaLogResult,
    }),

// This WORKS but per jest docks `mockResolvedValue` is essentially syntactic sugar for this and
// just a quick out of the mocked value looks pretty simliar (though didn't walk it all thru) 🤷 
    invoke: jest.fn().mockImplementation(() => Promise.resolve({
      Payload: JSON.stringify(lambdaPayload),
      FunctionError: lambdaError,
      LogResult: lambdaLogResult,
    })),
```


**When fp latest called into an imported function using older `0.0.16` would consistently fail with:**
```
2022-03-16T23:25:20.387Z	769ce665-0814-42b0-9804-bbaf0d61fc1f	ERROR	Invoke Error 	{
    "errorType": "SyntaxError",
    "errorMessage": "Unexpected token u in JSON at position 0",
    "stack": [
        "SyntaxError: Unexpected token u in JSON at position 0",
        "    at parse (<anonymous>)",
        "    at Object.apply (/var/task/node_modules/fp-latest/index.js:785:13)",
        "    at /var/task/node_modules/fp-latest/index.js:1976:15",
        "    at Array.reduce (<anonymous>)",
        "    at /var/task/node_modules/fp-latest/index.js:1972:23",
        "    at getAndEmitEvent (/var/task/src/eventReceivers/addressHandler/sharedHandlerCode.js:41:5)",
        "    at retreiveEvent (/var/task/src/eventReceivers/addressHandler/sharedHandlerCode.js:48:50)",
        "    at /var/task/src/eventReceivers/addressHandler/sharedHandlerCode.js:52:74",
        "    at /var/task/node_modules/@sullux/fp-light/index.js:150:19",
        "    at Generator.next (<anonymous>)"
    ]
}
```

I played around with the older imported function and narrowed it down to what appears to be the older  combo of `AsyncMap`, `awaitAll` and `toArray` not liking something new

```
  const pickFromCache = ({ cachedEvents, name }) => getPath(`cache.${name}`)(cachedEvents);

  const getAndEmitEvent = ({ apiCall, input }) =>
    apiCall(input).then(tap((event) => verifyAndIngressEvent(event)));

  const retreiveEvent = ({
    apiCall,
    name,
    input,
    cachedEvents,
  }) => pickFromCache({ cachedEvents, name }) || getAndEmitEvent({ apiCall, input });

  const retreiveEventsAsync = pipe(
    // Commented OUT section is older version that previously worked when imported/used in older version of fp latest
    // ({ config, input, cachedEvents }) => asyncMap(({ apiCall, name }) => retreiveEvent({
    //   apiCall, name, input, cachedEvents,
    // }), config),
    //awaitAll,
    //toArray,

    ({ config, input, cachedEvents }) => config.map(({ apiCall, name }) => retreiveEvent({ apiCall, name, input, cachedEvents })),
    awaitAll,
  );
```

**Comment by victorlearned** [comment]
Still having issues with promises. Seems like none of the tests actually combine any fp functions like they would actually be used in a pipe. I would expect something like this to work

```
    test('should resolve async function within a pipe', () => {
      function resolveAfter2Seconds() {
        return new Promise(resolve => {
          setTimeout(() => {
            resolve('resolved');
          }, 2000);
        });
      }

      async function asyncCall() {
        console.log('calling');
        const result = await resolveAfter2Seconds();
        console.log(result);
        // expected output: "resolved"
      }

      const input = { foo: 42 }
      const func = pipe(
        {
          foo: _.foo,
          testAsync: asyncCall,
        },
      )
      const result = async (input) => await func(input)
      expect(result(input)).toBe({ foo: 42, testAsync: 'resolved' })
    });
    ```

**Comment by victorlearned** [comment]
Another example of a function that continually returns an unresolved promise that pipe/resolve fails to await and just moves on without.


```
  const defaultConfig = () => getConfigs();

  const getConfigs = pipe(
    _.address,
    { state: _.state, county: _.county },
    getConfig,
    or(_, defaultConfig),
  );

  const getRequiredConfigs = pipe(
    // use address to get specific configs or default config
    { ..._, configs: getConfigs },
    // pull out the specific products & reportMappings from config
    {
      productTypes: _.configs.productTypes.products,
      reportMappingTypes: _.configs.reportMappingTypes,
    },
  );

 const processEvent = pipe(
    tap(({ events }) => console.log('Autoloaded events', JSON.stringify(events))),
    {
      products: _.events.products[0].data.products,
      orderType: _.events.products[0].data.orderType,
      address: _.events.addressValidated[0].data,
      fileId: _.event.data.fileId,
      update: _.update,
      // synthetic event
      productsCache: _.events.productsCreated[0].data,
      // synthetic event
      reportsCache: _.events.reports[0].data,
    },
    { ..._, ...getRequiredConfigs },
    // other stuff that eventually uses configs
);

**Comment by victorlearned** [comment]
So far seems to be working on the issues I've been seeing. 👍

**Comment by victorlearned** [comment]
Only lingering issue looks unrelated but seems like some reason when using `join` the seems like the `Symbol(sync): true` is left lingering. Do you scrub the symbols you're adding elsewhere? I would expect a `Object.entries` or something is being used for this since their not enumerable?
